---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
- apiGroups:
  - i.4ts.fr
  resources:
  - challenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - i.4ts.fr
  resources:
  - oraclechallenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
- apiGroups:
  - voyager.appscode.com
  resources:
  - ingress
  verbs:
  - create
  - delete
