---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - getambassador.io
  resources:
  - mappings
  verbs:
  - create
  - delete
- apiGroups:
  - getambassador.io
  resources:
  - tcpmappings
  verbs:
  - create
  - delete
- apiGroups:
  - i.4ts.fr
  resources:
  - challenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - i.4ts.fr
  resources:
  - instancedchallenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - i.4ts.fr
  resources:
  - oracleinstancedchallenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
