apiVersion: i.4ts.fr/v1
kind: Challenge
metadata:
  labels:
    app.kubernetes.io/name: atsi
    app.kubernetes.io/managed-by: kustomize
  name: challenge-sample-2
spec:
  name: Test Challenge Custom Part 2
  category: Test
  description: |
    This a test challenge
    Multiline string
    And a [link](https://www.google.com)
  initial_value: 75
  value_decay: 2
  minimum_value: 10
  max_attempts: 3
  decay_function: linear
  state: visible
  hints:
    - content: This is a free hint
      cost: 0
    - content: This is a hint
      cost: 10
      # requirements:
      #   prerequisites: [ 0 ]
  flag: 'flag{test}'
  type: i_dynamic
  requirements:
    prerequisites:
      - challenge-sample